version: '3.4'
services:
  nginx:
    image: nginx:1.20
    networks:
      - internal
    volumes:
      - ./nginx-sites.conf:/etc/nginx/templates/default.conf.template
    environment:
      - WORK_DIR=${WORK_DIR}
      - UID=${UID}
      - GID=${GID} 
      - NGINX_HOST=${MAGENTO_HOST}
      - NGINX_PORT=80
    restart: unless-stopped

  php:
    image: tanngoclai/php_mgt:7.4
    environment:
      UID: ${UID}
      GID: ${GID}
      # PHP_EXTENSIONS_ENABLE: ${PHP_EXTENSIONS_ENABLE}
    volumes:
      - ./php-custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ${WORK_DIR}:${WORK_DIR}:cached
    extra_hosts:
      - "host.docker.internal:host-gateway"
    links:
      - nginx:${MAGENTO_HOST}
    networks:
      - internal
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - internal
    restart: unless-stopped

  elasticseach:
    image: elasticsearch:7.9.1
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx512m
      - cluster.routing.allocation.disk.watermark.low=2gb
      - cluster.routing.allocation.disk.watermark.high=1gb
      - cluster.routing.allocation.disk.watermark.flood_stage=512mb
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - internal
    restart: unless-stopped
networks:
  internal:
    driver: bridge
volumes:
  elasticsearch_data: