<?php
/** @var Tyodio\Blog\Block\Exchange $block */
?>
<?php
$result = $block->getExchangerateInformation();
?>
<div class="container blog exchange">
<h1 id="label_try"><?php echo $block->getLabel(); ?> </h1>
<div id="show_exchange_rate">
    <div class="row">
        <?php
        foreach ($result as $temp) {
            $temp_xml = new SimpleXMLElement($temp);
            $date=strtotime($temp_xml->DateTime);
            ?>
            <div class="Ngày" style="margin: 20px;width: 100%;text-align: center;font-size: 16px;font-weight: 900;">Ngày cập nhật: <?php echo  date("d-m-Y", $date); ?></div>

            <table class="table table-striped table-bordered" style="font-size: 16px;">
                <thead>

                <tr class="classth fontS-11 " style="text-align:center;">
                    <th colspan="2" class="text-center">Ngoại tệ</th>
                    <th colspan="2" class="text-center">Mua
                    </th>
                    <th rowspan="2" class="text-center">
                        <div style="font-weight:bold; line-height: 53px;">
                            Bán
                        </div>
                    </th>
                </tr>
                <tr class="classth fontS-11" style="text-align:center;">
                    <th style="width:25%;" class="text-center">Tên ngoại tệ</th>
                    <th class="text-center">
                        Mã NT
                    </th>
                    <th style="width: 20%;" class="text-center">Tiền mặt</th>
                    <th style="width: 20%;" class="text-center">Chuyển khoản</th>
                </tr>
                </thead>
                <tbody>
            <?php
            foreach ($temp_xml->Exrate as $temp_exrate) {
                ?>
                <tr class="odd" >
                    <td style="text-align:left;">  <?php echo $temp_exrate['CurrencyName'] ?>  </td>
                    <td style="text-align:center;"><?php echo $temp_exrate['CurrencyCode'] ?></td>
                    <td><?php echo $temp_exrate['Buy'] ?> </td>
                    <td><?php echo $temp_exrate['Transfer'] ?></td>
                    <td><?php echo $temp_exrate['Sell'] ?></td>
                </tr>
                <?php
            }
            ?>

                </tbody>
            </table>


            <?php
        }
        ?>
    </div>
</div>
</div>
    